name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec-commenter
        uses: aquasecurity/tfsec-pr-commenter-action@v1.1.0-beta.1
        with:
          github_token: ${{ github.token }}
      - name: tfsec-validation
        uses: aquasecurity/tfsec-action@v1.0.2
        with:
          additional_args: --minimum-severity HIGH